name: Update M3U

on:
  schedule:
    - cron: "*/30 * * * *"  # كل 30 دقيقة
  workflow_dispatch: # للتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run update script
      run: python update.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add familytv.m3u
        git commit -m "Auto-update familytv.m3u"
        git push
